/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class olympics_Olympics */

#ifndef _Included_olympics_Olympics
#define _Included_olympics_Olympics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     olympics_Olympics
 * Method:    first
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jstring JNICALL Java_olympics_Olympics_first
  (JNIEnv *, jobject, jstring, jstring, jobjectArray);

/*
 * Class:     olympics_Olympics
 * Method:    second
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;IILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_olympics_Olympics_second
(JNIEnv*, jobject, jobjectArray, jint, jint, jstring);

/*
 * Class:     olympics_Olympics
 * Method:    third
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;IILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_olympics_Olympics_third
(JNIEnv*, jobject, jobjectArray, jint, jint, jstring);

/*
 * Class:     olympics_Olympics
 * Method:    fourth
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;IILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_olympics_Olympics_fourth
(JNIEnv*, jobject, jobjectArray, jint, jint, jstring);
#ifdef __cplusplus
}
#endif
#endif
